name: police-transcription-backend
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - fastapi=0.103.2
  - uvicorn=0.23.2
  - python-multipart=0.0.6
  - pydantic=2.4.2
  - pip
  - pip:
    - email-validator==2.0.0.post2
