name: police-transcription-backend
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - fastapi=0.103.2
  - uvicorn=0.23.2
  - python-multipart=0.0.6
  - pydantic=2.4.2
  - websockets=11.0.3
  - pip
  - transformers>=4.36
  - pytorch::pytorch>=2.1.1
  - pytorch::torchvision
  - pytorch::torchaudio
  - pip:
      - email-validator>=2.2.0
      - groq>=0.9.0
      - python-dotenv>=1.0.1
      - slowapi>=0.1.8
      - llm
      - llm-ollama
