name: police-transcription-backend
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - fastapi=0.103.2
  - uvicorn=0.23.2
  - python-multipart=0.0.6
  - pydantic=2.4.2
  - pip
  - transformers
  - optimum
  - pytorch
  - torchvision
  - torchaudio
  - pip:
    - email-validator==2.0.0.post2
    - accelerate
    - flash-attn
    - insanely-fast-whisper==0.0.15
